FROM oven/bun:1.3.0 AS base
WORKDIR /usr/local/app

FROM base AS install
RUN mkdir -p /temp/dev
COPY package.json bun.lock /temp/dev/
RUN cd /temp/dev && bun install --frozen-lockfile

FROM base AS prerelease
WORKDIR /usr/local/app
COPY --from=install /temp/dev/node_modules node_modules
COPY . .

ENV NODE_ENV development
CMD ["bun", "dev", "--host"]
