/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VitalsRouteImport } from './routes/vitals'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AdminUserRouteImport } from './routes/admin/user'
import { Route as AdminRoleRouteImport } from './routes/admin/role'

const VitalsRoute = VitalsRouteImport.update({
  id: '/vitals',
  path: '/vitals',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUserRoute = AdminUserRouteImport.update({
  id: '/admin/user',
  path: '/admin/user',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoleRoute = AdminRoleRouteImport.update({
  id: '/admin/role',
  path: '/admin/role',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/vitals': typeof VitalsRoute
  '/admin/role': typeof AdminRoleRoute
  '/admin/user': typeof AdminUserRoute
  '/api/$': typeof ApiSplatRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/vitals': typeof VitalsRoute
  '/admin/role': typeof AdminRoleRoute
  '/admin/user': typeof AdminUserRoute
  '/api/$': typeof ApiSplatRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/vitals': typeof VitalsRoute
  '/admin/role': typeof AdminRoleRoute
  '/admin/user': typeof AdminUserRoute
  '/api/$': typeof ApiSplatRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/vitals'
    | '/admin/role'
    | '/admin/user'
    | '/api/$'
    | '/admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/vitals'
    | '/admin/role'
    | '/admin/user'
    | '/api/$'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/vitals'
    | '/admin/role'
    | '/admin/user'
    | '/api/$'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  VitalsRoute: typeof VitalsRoute
  AdminRoleRoute: typeof AdminRoleRoute
  AdminUserRoute: typeof AdminUserRoute
  ApiSplatRoute: typeof ApiSplatRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vitals': {
      id: '/vitals'
      path: '/vitals'
      fullPath: '/vitals'
      preLoaderRoute: typeof VitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/user': {
      id: '/admin/user'
      path: '/admin/user'
      fullPath: '/admin/user'
      preLoaderRoute: typeof AdminUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/role': {
      id: '/admin/role'
      path: '/admin/role'
      fullPath: '/admin/role'
      preLoaderRoute: typeof AdminRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  VitalsRoute: VitalsRoute,
  AdminRoleRoute: AdminRoleRoute,
  AdminUserRoute: AdminUserRoute,
  ApiSplatRoute: ApiSplatRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
