/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as VitalsRouteRouteImport } from './routes/vitals/route'
import { Route as LabRouteRouteImport } from './routes/lab/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VitalsTokenRouteImport } from './routes/vitals/$token'
import { Route as LabCaseIdRouteImport } from './routes/lab/$caseId'
import { Route as ConsultationIdRouteImport } from './routes/consultation.$id'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AdminUserRouteImport } from './routes/admin/user'
import { Route as AdminRoleRouteImport } from './routes/admin/role'
import { Route as AdminOtpOverridesRouteImport } from './routes/admin/otp-overrides'
import { Route as HistoryPatientIdIndexRouteImport } from './routes/history.$patientId/index'
import { Route as HistoryPatientIdCaseIdRouteImport } from './routes/history.$patientId/$caseId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const VitalsRouteRoute = VitalsRouteRouteImport.update({
  id: '/vitals',
  path: '/vitals',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRouteRoute = LabRouteRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VitalsTokenRoute = VitalsTokenRouteImport.update({
  id: '/$token',
  path: '/$token',
  getParentRoute: () => VitalsRouteRoute,
} as any)
const LabCaseIdRoute = LabCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => LabRouteRoute,
} as any)
const ConsultationIdRoute = ConsultationIdRouteImport.update({
  id: '/consultation/$id',
  path: '/consultation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUserRoute = AdminUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRoleRoute = AdminRoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOtpOverridesRoute = AdminOtpOverridesRouteImport.update({
  id: '/otp-overrides',
  path: '/otp-overrides',
  getParentRoute: () => AdminRouteRoute,
} as any)
const HistoryPatientIdIndexRoute = HistoryPatientIdIndexRouteImport.update({
  id: '/history/$patientId/',
  path: '/history/$patientId/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryPatientIdCaseIdRoute = HistoryPatientIdCaseIdRouteImport.update({
  id: '/history/$patientId/$caseId',
  path: '/history/$patientId/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/lab': typeof LabRouteRouteWithChildren
  '/vitals': typeof VitalsRouteRouteWithChildren
  '/doctor': typeof DoctorRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/otp-overrides': typeof AdminOtpOverridesRoute
  '/admin/role': typeof AdminRoleRoute
  '/admin/user': typeof AdminUserRoute
  '/api/$': typeof ApiSplatRoute
  '/consultation/$id': typeof ConsultationIdRoute
  '/lab/$caseId': typeof LabCaseIdRoute
  '/vitals/$token': typeof VitalsTokenRoute
  '/history/$patientId/$caseId': typeof HistoryPatientIdCaseIdRoute
  '/history/$patientId': typeof HistoryPatientIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/lab': typeof LabRouteRouteWithChildren
  '/vitals': typeof VitalsRouteRouteWithChildren
  '/doctor': typeof DoctorRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/otp-overrides': typeof AdminOtpOverridesRoute
  '/admin/role': typeof AdminRoleRoute
  '/admin/user': typeof AdminUserRoute
  '/api/$': typeof ApiSplatRoute
  '/consultation/$id': typeof ConsultationIdRoute
  '/lab/$caseId': typeof LabCaseIdRoute
  '/vitals/$token': typeof VitalsTokenRoute
  '/history/$patientId/$caseId': typeof HistoryPatientIdCaseIdRoute
  '/history/$patientId': typeof HistoryPatientIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/lab': typeof LabRouteRouteWithChildren
  '/vitals': typeof VitalsRouteRouteWithChildren
  '/doctor': typeof DoctorRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/otp-overrides': typeof AdminOtpOverridesRoute
  '/admin/role': typeof AdminRoleRoute
  '/admin/user': typeof AdminUserRoute
  '/api/$': typeof ApiSplatRoute
  '/consultation/$id': typeof ConsultationIdRoute
  '/lab/$caseId': typeof LabCaseIdRoute
  '/vitals/$token': typeof VitalsTokenRoute
  '/history/$patientId/$caseId': typeof HistoryPatientIdCaseIdRoute
  '/history/$patientId/': typeof HistoryPatientIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/lab'
    | '/vitals'
    | '/doctor'
    | '/inventory'
    | '/login'
    | '/register'
    | '/admin/otp-overrides'
    | '/admin/role'
    | '/admin/user'
    | '/api/$'
    | '/consultation/$id'
    | '/lab/$caseId'
    | '/vitals/$token'
    | '/history/$patientId/$caseId'
    | '/history/$patientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/lab'
    | '/vitals'
    | '/doctor'
    | '/inventory'
    | '/login'
    | '/register'
    | '/admin/otp-overrides'
    | '/admin/role'
    | '/admin/user'
    | '/api/$'
    | '/consultation/$id'
    | '/lab/$caseId'
    | '/vitals/$token'
    | '/history/$patientId/$caseId'
    | '/history/$patientId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/lab'
    | '/vitals'
    | '/doctor'
    | '/inventory'
    | '/login'
    | '/register'
    | '/admin/otp-overrides'
    | '/admin/role'
    | '/admin/user'
    | '/api/$'
    | '/consultation/$id'
    | '/lab/$caseId'
    | '/vitals/$token'
    | '/history/$patientId/$caseId'
    | '/history/$patientId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LabRouteRoute: typeof LabRouteRouteWithChildren
  VitalsRouteRoute: typeof VitalsRouteRouteWithChildren
  DoctorRoute: typeof DoctorRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ConsultationIdRoute: typeof ConsultationIdRoute
  HistoryPatientIdCaseIdRoute: typeof HistoryPatientIdCaseIdRoute
  HistoryPatientIdIndexRoute: typeof HistoryPatientIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vitals': {
      id: '/vitals'
      path: '/vitals'
      fullPath: '/vitals'
      preLoaderRoute: typeof VitalsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vitals/$token': {
      id: '/vitals/$token'
      path: '/$token'
      fullPath: '/vitals/$token'
      preLoaderRoute: typeof VitalsTokenRouteImport
      parentRoute: typeof VitalsRouteRoute
    }
    '/lab/$caseId': {
      id: '/lab/$caseId'
      path: '/$caseId'
      fullPath: '/lab/$caseId'
      preLoaderRoute: typeof LabCaseIdRouteImport
      parentRoute: typeof LabRouteRoute
    }
    '/consultation/$id': {
      id: '/consultation/$id'
      path: '/consultation/$id'
      fullPath: '/consultation/$id'
      preLoaderRoute: typeof ConsultationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/user': {
      id: '/admin/user'
      path: '/user'
      fullPath: '/admin/user'
      preLoaderRoute: typeof AdminUserRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/role': {
      id: '/admin/role'
      path: '/role'
      fullPath: '/admin/role'
      preLoaderRoute: typeof AdminRoleRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/otp-overrides': {
      id: '/admin/otp-overrides'
      path: '/otp-overrides'
      fullPath: '/admin/otp-overrides'
      preLoaderRoute: typeof AdminOtpOverridesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/history/$patientId/': {
      id: '/history/$patientId/'
      path: '/history/$patientId'
      fullPath: '/history/$patientId'
      preLoaderRoute: typeof HistoryPatientIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$patientId/$caseId': {
      id: '/history/$patientId/$caseId'
      path: '/history/$patientId/$caseId'
      fullPath: '/history/$patientId/$caseId'
      preLoaderRoute: typeof HistoryPatientIdCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminOtpOverridesRoute: typeof AdminOtpOverridesRoute
  AdminRoleRoute: typeof AdminRoleRoute
  AdminUserRoute: typeof AdminUserRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminOtpOverridesRoute: AdminOtpOverridesRoute,
  AdminRoleRoute: AdminRoleRoute,
  AdminUserRoute: AdminUserRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface LabRouteRouteChildren {
  LabCaseIdRoute: typeof LabCaseIdRoute
}

const LabRouteRouteChildren: LabRouteRouteChildren = {
  LabCaseIdRoute: LabCaseIdRoute,
}

const LabRouteRouteWithChildren = LabRouteRoute._addFileChildren(
  LabRouteRouteChildren,
)

interface VitalsRouteRouteChildren {
  VitalsTokenRoute: typeof VitalsTokenRoute
}

const VitalsRouteRouteChildren: VitalsRouteRouteChildren = {
  VitalsTokenRoute: VitalsTokenRoute,
}

const VitalsRouteRouteWithChildren = VitalsRouteRoute._addFileChildren(
  VitalsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LabRouteRoute: LabRouteRouteWithChildren,
  VitalsRouteRoute: VitalsRouteRouteWithChildren,
  DoctorRoute: DoctorRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiSplatRoute: ApiSplatRoute,
  ConsultationIdRoute: ConsultationIdRoute,
  HistoryPatientIdCaseIdRoute: HistoryPatientIdCaseIdRoute,
  HistoryPatientIdIndexRoute: HistoryPatientIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
