/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VitalsRouteImport } from './routes/vitals'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
<<<<<<< HEAD
import { Route as DoctorRouteImport } from './routes/doctor'
=======
import { Route as AdminRouteImport } from './routes/admin'
>>>>>>> origin/main
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsultationIdRouteImport } from './routes/consultation.$id'
import { Route as ApiSplatRouteImport } from './routes/api/$'

const VitalsRoute = VitalsRouteImport.update({
  id: '/vitals',
  path: '/vitals',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
<<<<<<< HEAD
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
=======
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
>>>>>>> origin/main
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationIdRoute = ConsultationIdRouteImport.update({
  id: '/consultation/$id',
  path: '/consultation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
<<<<<<< HEAD
  '/doctor': typeof DoctorRoute
=======
  '/admin': typeof AdminRoute
>>>>>>> origin/main
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/vitals': typeof VitalsRoute
  '/api/$': typeof ApiSplatRoute
  '/consultation/$id': typeof ConsultationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
<<<<<<< HEAD
  '/doctor': typeof DoctorRoute
=======
  '/admin': typeof AdminRoute
>>>>>>> origin/main
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/vitals': typeof VitalsRoute
  '/api/$': typeof ApiSplatRoute
  '/consultation/$id': typeof ConsultationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
<<<<<<< HEAD
  '/doctor': typeof DoctorRoute
=======
  '/admin': typeof AdminRoute
>>>>>>> origin/main
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/vitals': typeof VitalsRoute
  '/api/$': typeof ApiSplatRoute
  '/consultation/$id': typeof ConsultationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
<<<<<<< HEAD
  fullPaths:
    | '/'
    | '/doctor'
    | '/login'
    | '/register'
    | '/vitals'
    | '/api/$'
    | '/consultation/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/doctor'
    | '/login'
    | '/register'
    | '/vitals'
    | '/api/$'
    | '/consultation/$id'
  id:
    | '__root__'
    | '/'
    | '/doctor'
=======
  fullPaths: '/' | '/admin' | '/login' | '/register' | '/vitals' | '/api/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/login' | '/register' | '/vitals' | '/api/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
>>>>>>> origin/main
    | '/login'
    | '/register'
    | '/vitals'
    | '/api/$'
<<<<<<< HEAD
    | '/consultation/$id'
=======
>>>>>>> origin/main
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
<<<<<<< HEAD
  DoctorRoute: typeof DoctorRoute
=======
  AdminRoute: typeof AdminRoute
>>>>>>> origin/main
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  VitalsRoute: typeof VitalsRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ConsultationIdRoute: typeof ConsultationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vitals': {
      id: '/vitals'
      path: '/vitals'
      fullPath: '/vitals'
      preLoaderRoute: typeof VitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
<<<<<<< HEAD
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
=======
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
>>>>>>> origin/main
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation/$id': {
      id: '/consultation/$id'
      path: '/consultation/$id'
      fullPath: '/consultation/$id'
      preLoaderRoute: typeof ConsultationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
<<<<<<< HEAD
  DoctorRoute: DoctorRoute,
=======
  AdminRoute: AdminRoute,
>>>>>>> origin/main
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  VitalsRoute: VitalsRoute,
  ApiSplatRoute: ApiSplatRoute,
  ConsultationIdRoute: ConsultationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
