name: Redeploy Staging

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  medc-staging:
    runs-on: medc
    env:
      DOCKER_HOST: unix:///run/user/1003/docker.sock
    steps:
      - name: Pull repo and deploy
        run: |
          cd /opt/services/team-medc
          git fetch origin main
          git checkout main
          git reset --hard origin/main
          docker compose --profile prod up --build -d
